apiVersion: v1
kind: Service
metadata:
  name: simple-market-app-backend
  namespace: kube-system
  labels:
    app: simple-market-app-backend
    node: sanchezkubenode
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: http
      name: adonisjs
  selector:
    app: simple-market-app-backend