apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-market-app-backend
  namespace: kube-system
  labels:
    app: simple-market-app-backend
    node: sanchezkubenode
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-market-app-backend
  template:
    metadata:
      labels:
        app: simple-market-app-backend
    spec:
      containers:
        - name: simple-market-app-backend
          image: leopimentel/simple-market-backend:$COMMIT_SHA1
          ports:
            - containerPort: 3030
---
apiVersion: v1
kind: Service
metadata:
  name: simple-market-app-backend
  namespace: kube-system
  labels:
    app: simple-market-app-backend
    node: sanchezkubenode
spec:
  selector:
    app: simple-market-app-backend
  type: LoadBalancer
  ports:
    - port: 3036
      targetPort: 3030