apiVersion: v1
kind: Service
metadata:
  name: simple-market-app-backend
  namespace: kube-system
  labels:
    app: simple-market-app-backend
    node: sanchezkubenode
spec:
  type: ClusterIP
  ports:
    - port: 3030
      targetPort: adonis
      name: adonis
  selector:
    app: simple-market-app-backend
    name: adonis