apiVersion: v1
kind: Service
metadata:
  name: simple-market-app-backend
  namespace: kube-system
  labels:
    app: simple-market-app-backend
    node: sanchezkubenode
spec:
  ports:
  - name: "3033"
    port: 3033
    localPort: 3000
  selector:
    app: simple-market-app-backend
    name: adonisjs
  type: NodePort